### PR TITLE
Remove Debug flag

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@martinRenou you need to pass `-D CMAKE_BUILD_TYPE=Release` to the cmake command.

**Comment by martinRenou** [comment]
Thanks!

**Comment by SylvainCorlay** [comment]
I think the test failure is unrelated. It is probably due to the new kernel nudging thing, which causes more kernel info replies to be sent.

**Comment by martinRenou** [comment]
Yeah we've seen this failure multiple times, I'll merge

**Pull request merged**
